### ISSUE TITLE
Change instances of "Smallpiece" -> "Smallpeice"

### ISSUE THREAD

**Issue by nmalky** [sourcebots/website#23]
Is the current spelling ("Smallpiece") intentional?
See: https://github.com/search?q=org%3Asourcebots+smallpiece&type=Code

**Comment by kierdavis** [comment]
I believe not; the correct spelling (according to their [website](https://www.smallpeicetrust.org.uk)) is "Smallpeice". So I agree we should change all instances of "Smallpiece" to "Smallpeice". Thanks for spotting this!

**Comment by RealOrangeOne** [comment]
Fixed in #25
