### ISSUE TITLE
SourceBots logo doesn't work well as a favicon

### ISSUE THREAD

**Issue by PeterJCLaw** [sourcebots/website#6]
IMO the logo is _far_ too detailed to use as a favicon.

Guidance for [flags](https://www.youtube.com/watch?v=pnv5iKB2hl4), which seems relevant here, is to fit your design into a 1" by 1.5" rectangle and then hold it at arms length. Obviously we've got a square rather than a rectangle, but the same idea applies -- our current logo is much to busy for detail to stand out at that scale.

Here are some alternatives:
![favicons](https://user-images.githubusercontent.com/336212/35196611-7e60dc08-fecc-11e7-96d1-07ca1ff345b9.png)

Personally I'm in favour of the second in that list -- the one which is just a diode; mostly because it's really clear and avoids lettering, even though it's arguably less obvious what it means.

**Comment by RealOrangeOne** [comment]
I agree with the second. Mostly because I've got no idea what the 3rd is of, and the rest look a bit, dull.

**Comment by PeterJCLaw** [comment]
The third and fifth feature the switch which is on the right of the text in the current logo. I agree that it's not very clear at this size! I'll put together a PR which uses the diode version.

**Comment by Adimote** [comment]
+1 on the second
